### ISSUE TITLE
String Session Issue

### ISSUE THREAD

**Issue by Getol99** [kastaid/getter#1]
Hi Kastaid,
I'm running your 'getter' on kali linux
Why can't i run python3 -m getter or python3 -m run --watch even if there is STRING SESSION on my app.py?
These are my screenshots for the errors :
1. My STRING SESSION is already there
![Capture](https://user-images.githubusercontent.com/92920817/156116933-7cad4e23-403f-4b36-9c7f-b0547f760ef6.PNG)
2. The "STRING SESSION empty" erros is still comes up
![Capture2](https://user-images.githubusercontent.com/92920817/156117053-e9fab0e3-f910-4722-9be4-e11d84387e12.png)

Waiting for your solution . . .

**Comment by notudope** [comment]
> Hi Kastaid, I'm running your 'getter' on kali linux Why can't i run python3 -m getter or python3 -m run --watch even if there is STRING SESSION on my app.py? These are my screenshots for the errors :
> 
> 1. My STRING SESSION is already there
>    ![Capture](https://user-images.githubusercontent.com/92920817/156116933-7cad4e23-403f-4b36-9c7f-b0547f760ef6.PNG)
> 2. The "STRING SESSION empty" erros is still comes up
>    ![Capture2](https://user-images.githubusercontent.com/92920817/156117053-e9fab0e3-f910-4722-9be4-e11d84387e12.png)
> 
> Waiting for your solution . . .

First generate STRING_SESSION use this https://github.com/kastaid/getter#string_session

Then, put all together `API_ID`, `API_HASH` etc in `config.env`
Example config see here https://github.com/kastaid/getter/blob/main/sample_config.env

**Comment by Getol99** [comment]
Okay, I'll try it first 👍

**Comment by Getol99** [comment]
> Okay, I'll try it first 👍
I'm really sorry, I didn't understand how to use .update deploy to update to the latest version
Already do the new git clone, but the version is still 0.0.1
New to this world of code btw :D
![Capture](https://user-images.githubusercontent.com/92920817/156122236-61c206c0-4521-4376-8d18-919b578193db.PNG)

**Comment by notudope** [comment]
> > Okay, I'll try it first 👍
> > I'm really sorry, I didn't understand how to use .update deploy to update to the latest version
> > Already do the new git clone, but the version is still 0.0.1
> > New to this world of code btw :D
> > ![Capture](https://user-images.githubusercontent.com/92920817/156122236-61c206c0-4521-4376-8d18-919b578193db.PNG)

Check version in __init__.py: `__version__`

**Comment by Getol99** [comment]
> Check version in **init**.py: `__version__`

Thank You, I'm running on the latest version then
![Capture](https://user-images.githubusercontent.com/92920817/156125231-a74eba77-ec25-4cd0-bc97-b802c47cd1f5.PNG)
 
 Again, I already adding my API_ID, API_HASH, and STRING SESSION in sample_config.env
![Capture2](https://user-images.githubusercontent.com/92920817/156125378-0a265715-d2c1-4df6-99d2-8431131f713b.png)

But new error with that STRING SESSION comes like this
![Capture3](https://user-images.githubusercontent.com/92920817/156125472-be49cdd8-9d65-4193-8aab-0265bfc5ebed.PNG)

**Comment by Getol99** [comment]
By the way, I'm generating STRING SESSION on python3 session.py. Is that why these errors came up again and again?

**Comment by notudope** [comment]
> > Check version in **init**.py: `__version__`
> 
> Thank You, I'm running on the latest version then ![Capture](https://user-images.githubusercontent.com/92920817/156125231-a74eba77-ec25-4cd0-bc97-b802c47cd1f5.PNG)
> 
> Again, I already adding my API_ID, API_HASH, and STRING SESSION in sample_config.env ![Capture2](https://user-images.githubusercontent.com/92920817/156125378-0a265715-d2c1-4df6-99d2-8431131f713b.png)
> 
> But new error with that STRING SESSION comes like this ![Capture3](https://user-images.githubusercontent.com/92920817/156125472-be49cdd8-9d65-4193-8aab-0265bfc5ebed.PNG)

Thanks for report, bug fixed. Force update repo again follow instructions above. Then don't forget create file `config.env` and fills with your choice.

More discussion join https://t.me/kastaot

**Comment by Getol99** [comment]
Thank you so much!
